<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>

    <p>Ниже представлен обзорный список всех описанных в данной статье кодов ответа:</p>
    
    <ul>
        <li><a href="#1xx">1xx: Informational</a> (информационные):
        <ul>
            <li><a href="#100">100 Continue</a> («продолжай»)<sup id="cite_ref-3digits_2-0" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-0" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#101">101 Switching Protocols</a> («переключение протоколов»)<sup id="cite_ref-3digits_2-1" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-1" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#102">102 Processing</a> («идёт обработка»).</li>
        </ul>
        </li>
        <li><a href="#2xx">2xx: Success</a> (успешно):
        <ul>
            <li><a href="#200">200 OK</a> («хорошо»)<sup id="cite_ref-3digits_2-2" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-2" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#201">201 Created</a> («создано»)<sup id="cite_ref-3digits_2-3" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-3" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup><sup id="cite_ref-webdav_4_2_5_4-0" class="reference"><a href="#cite_note-webdav_4_2_5-4">[4]</a></sup>.</li>
            <li><a href="#202">202 Accepted</a> («принято»)<sup id="cite_ref-3digits_2-4" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-4" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#203">203 Non-Authoritative Information</a> («информация не авторитетна»)<sup id="cite_ref-3digits_2-5" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-5" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#204">204 No Content</a> («нет содержимого»)<sup id="cite_ref-3digits_2-6" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-6" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#205">205 Reset Content</a> («сбросить содержимое»)<sup id="cite_ref-3digits_2-7" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-7" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#206">206 Partial Content</a> («частичное содержимое»)<sup id="cite_ref-3digits_2-8" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-8" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#207">207 Multi-Status</a> («многостатусный»)<sup id="cite_ref-webdav_10_5-0" class="reference"><a href="#cite_note-webdav_10-5">[5]</a></sup>.</li>
            <li><a href="#226">226 IM Used</a> («использовано IM»).</li>
        </ul>
        </li>
        <li><a href="#3xx">3xx: Redirection</a> (перенаправление):
        <ul>
            <li><a href="#300">300 Multiple Choices</a> («множество выборов»)<sup id="cite_ref-3digits_2-9" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_10_3_6-0" class="reference"><a href="#cite_note-rfc2616_10_3-6">[6]</a></sup>.</li>
            <li><a href="#301">301 Moved Permanently</a> («перемещено навсегда»)<sup id="cite_ref-3digits_2-10" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_10_3_6-1" class="reference"><a href="#cite_note-rfc2616_10_3-6">[6]</a></sup>.</li>
            <li><a href="#302">302 Moved Temporarily</a> («перемещено временно»)<sup id="cite_ref-3digits_2-11" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_10_3_6-2" class="reference"><a href="#cite_note-rfc2616_10_3-6">[6]</a></sup>.</li>
            <li><a href="#302">302 Found</a> («найдено»)<sup id="cite_ref-rfc2616_10_3_6-3" class="reference"><a href="#cite_note-rfc2616_10_3-6">[6]</a></sup>.</li>
            <li><a href="#303">303 See Other</a> (смотреть другое)<sup id="cite_ref-3digits_2-12" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_10_3_6-4" class="reference"><a href="#cite_note-rfc2616_10_3-6">[6]</a></sup>.</li>
            <li><a href="#304">304 Not Modified</a> (не изменялось)<sup id="cite_ref-3digits_2-13" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_10_3_6-5" class="reference"><a href="#cite_note-rfc2616_10_3-6">[6]</a></sup>.</li>
            <li><a href="#305">305 Use Proxy</a> («использовать прокси»)<sup id="cite_ref-3digits_2-14" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_10_3_6-6" class="reference"><a href="#cite_note-rfc2616_10_3-6">[6]</a></sup>.</li>
            <li><a href="#306">306</a>&#160;— <i>зарезервировано</i> (код использовался только в ранних спецификациях)<sup id="cite_ref-rfc2616_10_3_6-7" class="reference"><a href="#cite_note-rfc2616_10_3-6">[6]</a></sup>.</li>
            <li><a href="#307">307 Temporary Redirect</a> («временное перенаправление»)<sup id="cite_ref-rfc2616_10_3_6-8" class="reference"><a href="#cite_note-rfc2616_10_3-6">[6]</a></sup>.</li>
        </ul>
        </li>
        <li><a href="#4xx">4xx: Client Error</a> (ошибка клиента):
        <ul>
            <li><a href="#400">400 Bad Request</a> («плохой, неверный запрос»)<sup id="cite_ref-3digits_2-15" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-9" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup><sup id="cite_ref-webdav_4_2_5_4-1" class="reference"><a href="#cite_note-webdav_4_2_5-4">[4]</a></sup>.</li>
            <li><a href="#401">401 Unauthorized</a> («не авторизован»)<sup id="cite_ref-3digits_2-16" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-10" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#402">402 Payment Required</a> («необходима оплата»)<sup id="cite_ref-3digits_2-17" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-11" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#403">403 Forbidden</a> («запрещено»)<sup id="cite_ref-3digits_2-18" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-12" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#404">404 Not Found</a> («не найдено»)<sup id="cite_ref-3digits_2-19" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-13" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#405">405 Method Not Allowed</a> («метод не поддерживается»)<sup id="cite_ref-3digits_2-20" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-14" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#406">406 Not Acceptable</a> («неприемлемо»)<sup id="cite_ref-3digits_2-21" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-15" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#407">407 Proxy Authentication Required</a> («необходима аутентификация прокси»)<sup id="cite_ref-3digits_2-22" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-16" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#408">408 Request Timeout</a> («истекло время ожидания»)<sup id="cite_ref-3digits_2-23" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-17" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#409">409 Conflict</a> («конфликт»)<sup id="cite_ref-3digits_2-24" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-18" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup><sup id="cite_ref-webdav_4_2_5_4-2" class="reference"><a href="#cite_note-webdav_4_2_5-4">[4]</a></sup>.</li>
            <li><a href="#410">410 Gone</a> («удалён»)<sup id="cite_ref-3digits_2-25" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-19" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#411">411 Length Required</a> («необходима длина»)<sup id="cite_ref-3digits_2-26" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-20" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#412">412 Precondition Failed</a> («условие ложно»)<sup id="cite_ref-3digits_2-27" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-21" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup><sup id="cite_ref-webdav_4_3_1_1_7-0" class="reference"><a href="#cite_note-webdav_4_3_1_1-7">[7]</a></sup>.</li>
            <li><a href="#413">413 Request Entity Too Large</a> («размер запроса слишком велик»)<sup id="cite_ref-3digits_2-28" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-22" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#414">414 Request-URI Too Large</a> («запрашиваемый <a href="/wiki/URI" title="URI">URI</a> слишком длинный»)<sup id="cite_ref-3digits_2-29" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-23" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#415">415 Unsupported Media Type</a> («неподдерживаемый тип данных»)<sup id="cite_ref-3digits_2-30" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-24" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#416">416 Requested Range Not Satisfiable</a> («запрашиваемый диапазон не достижим»)<sup id="cite_ref-rfc2616_3-25" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP#417" title="Список кодов состояния HTTP">417 Expectation Failed</a> («ожидаемое неприемлемо»)<sup id="cite_ref-rfc2616_3-26" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#422">422 Unprocessable Entity</a> («необрабатываемый экземпляр»).</li>
            <li><a href="#423">423 Locked</a> («заблокировано»).</li>
            <li><a href="#424">424 Failed Dependency</a> («невыполненная зависимость»).</li>
            <li><a href="#425">425 Unordered Collection</a> («неупорядоченный набор»)<sup id="cite_ref-webdav_5_3_2_8-0" class="reference"><a href="#cite_note-webdav_5_3_2-8">[8]</a></sup>.</li>
            <li><a href="#426">426 Upgrade Required</a> («необходимо обновление»).</li>
            <li><a href="#428">428 Precondition Required</a> («необходимо предусловие»)<sup id="cite_ref-rfc6585_9-0" class="reference"><a href="#cite_note-rfc6585-9">[9]</a></sup>.</li>
            <li><a href="#429">429 Too Many Requests</a> («слишком много запросов»)<sup id="cite_ref-rfc6585_9-1" class="reference"><a href="#cite_note-rfc6585-9">[9]</a></sup>.</li>
            <li><a href="#431">431 Request Header Fields Too Large</a> («поля заголовка запроса слишком большие»)<sup id="cite_ref-rfc6585_9-2" class="reference"><a href="#cite_note-rfc6585-9">[9]</a></sup>.</li>
            <li><a href="/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP#434" title="Список кодов состояния HTTP">434 Requested host unavailable.</a> («Запрашиваемый адрес недоступен»)<span class="noprint"><sup><a href="/wiki/%D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F:%D0%A1%D1%81%D1%8B%D0%BB%D0%BA%D0%B8_%D0%BD%D0%B0_%D0%B8%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%B8" title="Википедия:Ссылки на источники">[<i>источник&#160;не&#160;указан&#160;1122&#160;дня</i>]</a></sup></span></li>
            <li>444 Закрывает соединение без передачи заголовка ответа. Нестандартный код <sup id="cite_ref-10" class="reference"><a href="#cite_note-10">[10]</a></sup></li>
            <li><a href="#449">449 Retry With</a> («повторить с»)<sup id="cite_ref-MSDN_WEBDAV_2_2_6_1-1" class="reference"><a href="#cite_note-MSDN_WEBDAV_2_2_6-1">[1]</a></sup>.</li>
            <li><a href="/wiki/HTTP_451" title="HTTP 451">451 Unavailable For Legal Reasons</a> («недоступно по юридическим причинам»)<sup id="cite_ref-http451_11-0" class="reference"><a href="#cite_note-http451-11">[11]</a></sup>.</li>
        </ul>
        </li>
        <li><a href="#5xx">5xx: Server Error</a> (ошибка сервера):
        <ul>
            <li><a href="#500">500 Internal Server Error</a> («внутренняя ошибка сервера»)<sup id="cite_ref-3digits_2-31" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-27" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#501">501 Not Implemented</a> («не реализовано»)<sup id="cite_ref-3digits_2-32" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-28" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#502">502 Bad Gateway</a> («плохой, ошибочный шлюз»)<sup id="cite_ref-3digits_2-33" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-29" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#503">503 Service Unavailable</a> («сервис недоступен»)<sup id="cite_ref-3digits_2-34" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-30" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#504">504 Gateway Timeout</a> («шлюз не отвечает»)<sup id="cite_ref-3digits_2-35" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-31" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#505">505 HTTP Version Not Supported</a> («версия HTTP не поддерживается»)<sup id="cite_ref-3digits_2-36" class="reference"><a href="#cite_note-3digits-2">[2]</a></sup><sup id="cite_ref-rfc2616_3-32" class="reference"><a href="#cite_note-rfc2616-3">[3]</a></sup>.</li>
            <li><a href="#506">506 Variant Also Negotiates</a> («вариант тоже проводит согласование»)<sup id="cite_ref-rfc2295_8_1_12-0" class="reference"><a href="#cite_note-rfc2295_8_1-12">[12]</a></sup></li>
            <li><a href="#507">507 Insufficient Storage</a> («переполнение хранилища»).</li>
            <li><a href="#508">508 Loop Detected</a> («обнаружено бесконечное перенаправление»)<sup id="cite_ref-webdav_7_1_13-0" class="reference"><a href="#cite_note-webdav_7_1-13">[13]</a></sup></li>
            <li><a href="#509">509 Bandwidth Limit Exceeded</a> («исчерпана пропускная ширина канала»).</li>
            <li><a href="#510">510 Not Extended</a> («не расширено»).</li>
            <li><a href="#511">511 Network Authentication Required</a> («требуется сетевая аутентификация»)<sup id="cite_ref-rfc6585_9-3" class="reference"><a href="#cite_note-rfc6585-9">[9]</a></sup>.</li>
        </ul>
        </li>
    </ul>
    <h2><span class="mw-headline" id=".D0.9E.D0.BF.D0.B8.D1.81.D0.B0.D0.BD.D0.B8.D0.B5_.D0.BA.D0.BE.D0.B4.D0.BE.D0.B2">Описание кодов</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&amp;veaction=edit&amp;vesection=2" class="mw-editsection-visualeditor" title="Редактировать раздел «Описание кодов»">править</a><span class="mw-editsection-divider"> | </span><a href="/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&amp;action=edit&amp;section=2" title="Редактировать раздел «Описание кодов»">править вики-текст</a><span class="mw-editsection-bracket">]</span></span></h2>
    <h3><span class="mw-headline" id=".D0.98.D0.BD.D1.84.D0.BE.D1.80.D0.BC.D0.B0.D1.86.D0.B8.D0.BE.D0.BD.D0.BD.D1.8B.D0.B5">Информационные</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&amp;veaction=edit&amp;vesection=3" class="mw-editsection-visualeditor" title="Редактировать раздел «Информационные»">править</a><span class="mw-editsection-divider"> | </span><a href="/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&amp;action=edit&amp;section=3" title="Редактировать раздел «Информационные»">править вики-текст</a><span class="mw-editsection-bracket">]</span></span></h3>
    <p>
        <span id="1xx"></span> В этот класс выделены коды, информирующие о процессе передачи. При работе через протокол версии 1.0 сообщения с такими кодами должны игнорироваться. В версии 1.1 клиент должен быть готов принять этот класс сообщений как обычный ответ, но серверу отправлять что-либо не нужно. Сами сообщения от сервера содержат только стартовую строку ответа и, если требуется, несколько специфичных для ответа полей заголовка. <a href="/wiki/%D0%9F%D1%80%D0%BE%D0%BA%D1%81%D0%B8-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80" title="Прокси-сервер">Прокси-сервера</a> подобные сообщения должны отправлять дальше от сервера к клиенту.
    </p>
    <ul>
        <li><span id="100"></span>100 Continue&#160;— сервер удовлетворён начальными сведениями о запросе, клиент может продолжать пересылать заголовки. Появился в HTTP/1.1.</li>
        <li><span id="101"></span>101 Switching Protocols&#160;— сервер предлагает перейти на более подходящий для указанного ресурса протокол; список предлагаемых протоколов сервер обязательно указывает в поле заголовка <code>Upgrade</code>. Если клиента это заинтересует, то он посылает новый запрос с указанием другого протокола. Появился в HTTP/1.1.</li>
        <li><span id="102"></span>102 Processing&#160;— запрос принят, но на его обработку понадобится длительное время. Используется сервером, чтобы клиент не разорвал соединение из-за превышения времени ожидания. Клиент при получении такого ответа должен сбросить таймер и дожидаться следующей команды в обычном режиме. Появился в <i><a href="/wiki/WebDAV" title="WebDAV">WebDAV</a></i>.</li>
    </ul>
    <h3><span class="mw-headline" id=".D0.A3.D1.81.D0.BF.D0.B5.D1.85">Успех</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&amp;veaction=edit&amp;vesection=4" class="mw-editsection-visualeditor" title="Редактировать раздел «Успех»">править</a><span class="mw-editsection-divider"> | </span><a href="/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&amp;action=edit&amp;section=4" title="Редактировать раздел «Успех»">править вики-текст</a><span class="mw-editsection-bracket">]</span></span></h3>
    <p>
        <span id="2xx"></span> Сообщения данного класса информируют о случаях успешного принятия и обработки запроса клиента. В зависимости от статуса сервер может ещё передать заголовки и тело сообщения.
    </p>
    <ul>
        <li><span id="200"></span>200 OK&#160;— успешный запрос. Если клиентом были запрошены какие-либо данные, то они находятся в заголовке и/или теле сообщения. Появился в HTTP/1.0.</li>
        <li><span id="201"></span>201 Created&#160;— в результате успешного выполнения запроса был создан новый ресурс. Сервер может указать адреса (их может быть несколько) созданного ресурса в теле ответа, при этом предпочтительный адрес указывается в заголовке <code>Location</code>. Серверу рекомендуется указывать в теле ответа характеристики созданного ресурса и его адреса, формат тела ответа определяется заголовком <code>Content-Type</code>. При обработке запроса, новый ресурс должен быть создан до отправки ответа клиенту, иначе следует использовать ответ с кодом <code><a href="#202">202</a></code>. Появился в HTTP/1.0.</li>
        <li><span id="202"></span>202 Accepted&#160;— запрос был принят на обработку, но она не завершена. Клиенту не обязательно дожидаться окончательной передачи сообщения, так как может быть начат очень долгий процесс. Появился в HTTP/1.0.</li>
        <li><span id="203"></span>203 Non-Authoritative Information&#160;— аналогично ответу <code><a href="#200">200</a></code>, но в этом случае передаваемая информация была взята не из первичного источника (резервной копии, другого сервера и&#160;т.&#160;д.) и поэтому может быть неактуальной. Появился в HTTP/1.1.</li>
        <li><span id="204"></span>204 No Content&#160;— сервер успешно обработал запрос, но в ответе были переданы только заголовки без тела сообщения. Клиент не должен обновлять содержимое документа, но может применить к нему полученные <a href="/wiki/%D0%9C%D0%B5%D1%82%D0%B0%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5" title="Метаданные">метаданные</a>. Появился в HTTP/1.0.</li>
        <li><span id="205"></span> 205 Reset Content&#160;— сервер обязывает клиента сбросить введённые пользователем данные. Тела сообщения сервер при этом не передаёт и документ обновлять не обязательно. Появился в HTTP/1.1.</li>
        <li><span id="206"></span> 206 Partial Content&#160;— сервер удачно выполнил <a href="/wiki/HTTP#.D0.A7.D0.B0.D1.81.D1.82.D0.B8.D1.87.D0.BD.D1.8B.D0.B5_GET" title="HTTP">частичный GET-запрос</a>, возвратив только часть сообщения. В заголовке <code>Content-Range</code> сервер указывает <a href="/wiki/%D0%97%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%B8_HTTP#.D0.91.D0.B0.D0.B9.D1.82.D0.BE.D0.B2.D1.8B.D0.B5_.D0.B4.D0.B8.D0.B0.D0.BF.D0.B0.D0.B7.D0.BE.D0.BD.D1.8B" title="Заголовки HTTP">байтовые диапазоны</a> содержимого. Особое внимание при работе с подобными ответами следует уделить кэшированию. Появился в HTTP/1.1. (<i><a href="/wiki/HTTP#.D0.94.D0.BE.D0.BA.D0.B0.D1.87.D0.BA.D0.B0_.D0.B8_.D1.84.D1.80.D0.B0.D0.B3.D0.BC.D0.B5.D0.BD.D1.82.D0.B0.D1.80.D0.BD.D0.BE.D0.B5_.D1.81.D0.BA.D0.B0.D1.87.D0.B8.D0.B2.D0.B0.D0.BD.D0.B8.D0.B5" title="HTTP">подробнее...</a></i>)</li>
        <li><span id="207"></span> 207 Multi-Status&#160;— сервер передаёт результаты выполнения сразу нескольких независимых операций. Они помещаются в само тело сообщения в виде <a href="/wiki/XML" title="XML">XML</a>-документа с объектом <code>multistatus</code>. Не рекомендуется размещать в этом объекте статусы из серии <code><a href="#1xx">1xx</a></code> из-за бессмысленности и избыточности. Появился в <i>WebDAV</i>.</li>
        <li><span id="226"></span> 226 IM Used&#160;— заголовок <code>A-IM</code> от клиента был успешно принят и сервер возвращает содержимое с учётом указанных параметров. Введено в <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc3229">RFC 3229</a> для дополнения протокола HTTP поддержкой <a href="/wiki/%D0%94%D0%B5%D0%BB%D1%8C%D1%82%D0%B0-%D0%BA%D0%BE%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5" title="Дельта-кодирование">дельта-кодирования</a>.</li>
    </ul>
    <h3><span class="mw-headline" id=".D0.9F.D0.B5.D1.80.D0.B5.D0.BD.D0.B0.D0.BF.D1.80.D0.B0.D0.B2.D0.BB.D0.B5.D0.BD.D0.B8.D0.B5">Перенаправление</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&amp;veaction=edit&amp;vesection=5" class="mw-editsection-visualeditor" title="Редактировать раздел «Перенаправление»">править</a><span class="mw-editsection-divider"> | </span><a href="/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&amp;action=edit&amp;section=5" title="Редактировать раздел «Перенаправление»">править вики-текст</a><span class="mw-editsection-bracket">]</span></span></h3>
    <p>
        <span id="3xx"></span> Коды этого класса сообщают клиенту, что для успешного выполнения операции необходимо сделать другой запрос, как правило, по другому <a href="/wiki/URI" title="URI">URI</a>. Из данного класса пять кодов <code><a href="#301">301</a></code>, <code><a href="#302">302</a></code>, <code><a href="#303">303</a></code>, <code><a href="#305">305</a></code> и <code><a href="#307">307</a></code> относятся непосредственно к перенаправлениям. Адрес, по которому клиенту следует произвести запрос, сервер указывает в заголовке <code>Location</code>. При этом допускается использование фрагментов в целевом URI.
    </p>
    <p>
        По последним стандартам клиент может производить перенаправление без запроса пользователя только если второй ресурс будет запрашиваться методом <code><a href="/wiki/HTTP#GET" title="HTTP">GET</a></code> или <code><a href="/wiki/HTTP#HEAD" title="HTTP">HEAD</a></code><sup id="cite_ref-rfc2616_10_3_6-9" class="reference"><a href="#cite_note-rfc2616_10_3-6">[6]</a></sup>. В предыдущих спецификациях говорилось, что для избежания круговых переходов пользователя следует спрашивать после 5-го подряд перенаправления<sup id="cite_ref-14" class="reference"><a href="#cite_note-14">[14]</a></sup>. При всех перенаправлениях, если метод запроса был не <code>HEAD</code>, то в тело ответа следует включить короткое гипертекстовое сообщение с целевым адресом, чтобы в случае ошибки пользователь смог сам произвести переход.
    </p>
    <p>
        Разработчики HTTP отмечают, что многие клиенты при перенаправлениях с кодами <code>301</code> и <code>302</code> ошибочно применяют метод <code>GET</code> ко второму ресурсу, несмотря на то, что к первому запрос был с иным методом (чаще всего PUT)<sup id="cite_ref-redirects-methods_15-0" class="reference"><a href="#cite_note-redirects-methods-15">[15]</a></sup>. Чтобы избежать недоразумений, в версии HTTP/1.1 были введены коды <code>303</code> и <code>307</code> и их рекомендовано использовать вместо <code>302</code>. Изменять метод нужно только если сервер ответил <code>303</code>. В остальных случаях следующий запрос производить с исходным методом.
    </p>
    <p>
        Поведение клиентов при различных перенаправлениях описано в таблице:
    </p>
    <table class="standard">
    <tr>
        <th>
            Статус ответа
        </th>
        <th>
            Кэширование
        </th>
        <th>
            Если метод не GET или HEAD
        </th>
    </tr>
    <tr>
        <td>
            <code><a href="#301">301 Moved Permanently</a></code>
        </td>
        <td>
            Можно как обычно.
        </td>
        <td rowspan="3">
            Спросить у пользователя подтверждения и запросить другой ресурс исходным методом.
        </td>
    </tr>
    <tr>
        <td>
            <tt><a href="#307">307 Temporary Redirect</a></tt>
        </td>
        <td rowspan="2">
            Можно только если указан заголовок <code>Cache-Control</code> или <code>Expires</code>.
        </td>
    </tr>
    <tr>
        <td>
            <tt><a href="#302">302 Found</a></tt> (HTTP/1.1)<br/>
            <span style="white-space: nowrap;"><tt><a href="#302">302 Moved Temporarily</a></tt> (HTTP/1.0)</span>
        </td>
    </tr>
    <tr>
        <td>
            <tt><a href="#303">303 See Other</a></tt>
        </td>
        <td>
            Нельзя.
        </td>
        <td>
            Перейти автоматически, но уже методом <code>GET</code>.
        </td>
    </tr>
    </table>
    <ul>
        <li><span id="300"></span> 300 Multiple Choices&#160;— по указанному URI существует несколько вариантов предоставления ресурса по типу <a href="/wiki/MIME" title="MIME">MIME</a>, по языку или по другим характеристикам. Сервер передаёт с сообщением список альтернатив, давая возможность сделать выбор клиенту автоматически или пользователю. Появился в HTTP/1.0.</li>
        <li><span id="301"></span><a href="/wiki/%D0%9A%D0%BE%D0%B4_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_301_%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB%D0%B0_HTTP" title="Код состояния 301 протокола HTTP">301 Moved Permanently</a>&#160;— запрошенный документ был окончательно перенесен на новый URI, указанный в поле <code>Location</code> заголовка. Некоторые клиенты некорректно ведут себя при обработке данного кода. Появился в HTTP/1.0.</li>
        <li><span id="302"></span> 302 Found, 302 Moved Temporarily&#160;— запрошенный документ временно доступен по другому URI, указанному в заголовке в поле <code>Location</code>. Этот код может быть использован, например, при <a href="/wiki/HTTP#.D0.A3.D0.BF.D1.80.D0.B0.D0.B2.D0.BB.D1.8F.D0.B5.D0.BC.D0.BE.D0.B5_.D1.81.D0.B5.D1.80.D0.B2.D0.B5.D1.80.D0.BE.D0.BC" title="HTTP">управляемом сервером согласовании содержимого</a>. Некоторые клиенты некорректно ведут себя при обработке данного кода. Введено в HTTP/1.0.</li>
        <li><span id="303"></span> 303 See Other&#160;— документ по запрошенному URI нужно запросить по адресу в поле <code>Location</code> заголовка с использованием метода <code>GET</code> несмотря даже на то, что первый запрашивался иным методом. Этот код был введён вместе с <code>307</code>-ым для избежания неоднозначности, чтобы сервер был уверен, что следующий ресурс будет запрошен методом <code>GET</code>. Например, на веб-странице есть поле ввода текста для быстрого перехода и поиска. После ввода данных браузер делает запрос методом <code>POST</code>, включая в тело сообщения введённый текст. Если обнаружен документ с введённым названием, то сервер отвечает кодом <code>303</code>, указав в заголовке <code>Location</code> его постоянный адрес. Тогда браузер гарантировано его запросит методом <code>GET</code> для получения содержимого. В противном случае сервер просто вернёт клиенту страницу с результатами поиска. Введено в HTTP/1.1.</li>
        <li><span id="304"></span> 304 Not Modified&#160;— сервер возвращает такой код, если клиент запросил документ методом <code>GET</code>, использовал заголовок <code>If-Modified-Since</code> или <code>If-None-Match</code> и документ не изменился с указанного момента. При этом сообщение сервера не должно содержать тела. Появился в HTTP/1.0.</li>
        <li><span id="305"></span> 305 Use Proxy&#160;— запрос к запрашиваемому ресурсу должен осуществляться через <a href="/wiki/%D0%9F%D1%80%D0%BE%D0%BA%D1%81%D0%B8-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80" title="Прокси-сервер">прокси-сервер</a>, URI которого указан в поле <code>Location</code> заголовка. Данный код ответа могут использовать только исходные HTTP-сервера (не прокси). Введено в HTTP/1.1.</li>
        <li><span id="306"></span> 306 (зарезервировано)&#160;— использовавшийся раньше код ответа, в настоящий момент зарезервирован. Упомянут в <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc2616">RFC 2616</a> (обновление HTTP/1.1).</li>
        <li><span id="307"></span> 307 Temporary Redirect&#160;— запрашиваемый ресурс на короткое время доступен по другому URI, указанный в поле <code>Location</code> заголовка. Метод запроса (GET/POST) менять не разрешается. Например, POST запрос должен быть отправлен по новому URI тем же методом POST. Этот код был введён вместе с 303 вместо 302-го для избежания неоднозначности. Введено в <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc2616">RFC 2616</a> (обновление HTTP/1.1).</li>
    </ul>
    <h3><span class="mw-headline" id=".D0.9E.D1.88.D0.B8.D0.B1.D0.BA.D0.B0_.D0.BA.D0.BB.D0.B8.D0.B5.D0.BD.D1.82.D0.B0">Ошибка клиента</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&amp;veaction=edit&amp;vesection=6" class="mw-editsection-visualeditor" title="Редактировать раздел «Ошибка клиента»">править</a><span class="mw-editsection-divider"> | </span><a href="/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&amp;action=edit&amp;section=6" title="Редактировать раздел «Ошибка клиента»">править вики-текст</a><span class="mw-editsection-bracket">]</span></span></h3>
    <p>
        <span id="4xx"></span> Класс кодов <code>4xx</code> предназначен для указания ошибок со стороны клиента. При использовании всех методов, кроме <code>HEAD</code>, сервер должен вернуть в теле сообщения гипертекстовое пояснение для пользователя.
    </p>
    <ul>
        <li><span id="400"></span> 400 Bad Request&#160;— сервер обнаружил в запросе клиента синтаксическую ошибку. Появился в HTTP/1.0.</li>
        <li><span id="401"></span> 401 Unauthorized&#160;— для доступа к запрашиваемому ресурсу требуется аутентификация. В заголовке ответ должен содержать поле <code>WWW-Authenticate</code> с перечнем условий аутентификации. Клиент может повторить запрос, включив в заголовок сообщения поле <code>Authorization</code> с требуемыми для аутентификации данными.</li>
        <li><span id="402"></span> 402 Payment Required&#160;— предполагается использовать в будущем. В настоящий момент не используется. Этот код предусмотрен для платных пользовательских сервисов, а не для <a href="/wiki/%D0%A5%D0%BE%D1%81%D1%82%D0%B8%D0%BD%D0%B3" title="Хостинг">хостинговых</a> компаний. Имеется в виду, что эта ошибка не будет выдана хостинговым провайдером в случае просроченной оплаты его услуг. Зарезервирован, начиная с HTTP/1.1.</li>
    </ul>
    <div class="thumb tright">
        <div class="thumbinner" style="width:302px;">
            <a href="/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Firefox_screenshot-HTTP_error_403.png" class="image"><img alt="" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Firefox_screenshot-HTTP_error_403.png/300px-Firefox_screenshot-HTTP_error_403.png" width="300" height="150" class="thumbimage" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Firefox_screenshot-HTTP_error_403.png/450px-Firefox_screenshot-HTTP_error_403.png 1.5x, //upload.wikimedia.org/wikipedia/commons/4/48/Firefox_screenshot-HTTP_error_403.png 2x" data-file-width="577" data-file-height="289"/></a>
            <div class="thumbcaption">
                <div class="magnify">
                    <a href="/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Firefox_screenshot-HTTP_error_403.png" class="internal" title="Увеличить"></a>
                </div>
                 Сервер вернул ошибку 403 при попытке просмотра директории «cgi-bin», доступ к которой был запрещён.
            </div>
        </div>
    </div>
    <ul>
        <li><span id="403"></span> 403 Forbidden<sup id="cite_ref-16" class="reference"><a href="#cite_note-16">[16]</a></sup> — сервер понял запрос, но он отказывается его выполнять из-за ограничений в доступе для клиента к указанному ресурсу. Если для доступа к ресурсу требуется аутентификация средствами HTTP, то сервер вернёт ответ <code><a href="#401">401</a></code>, или <code><a href="#407">407</a></code> при использовании прокси. В противном случае ограничения были заданы администратором сервера или разработчиком веб-приложения и могут быть любыми в зависимости от возможностей используемого <a href="/wiki/%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BD%D0%BE%D0%B5_%D0%BE%D0%B1%D0%B5%D1%81%D0%BF%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D0%B5" title="Программное обеспечение">программного обеспечения</a>. В любом случае клиенту следует сообщить причины отказа в обработке запроса. Наиболее вероятными причинами ограничения может послужить попытка доступа к системным ресурсам веб-сервера (например, файлам <code><a href="/wiki/.htaccess" title=".htaccess">.htaccess</a></code> или <code><a href="/wiki/.htpasswd" title=".htpasswd">.htpasswd</a></code>) или к файлам, доступ к которым был закрыт с помощью конфигурационных файлов, требование аутентификации не средствами HTTP, например, для доступа к <a href="/wiki/%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0_%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F_%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D0%BC%D1%8B%D0%BC" title="Система управления содержимым">системе управления содержимым</a> или разделу для зарегистрированных пользователей либо сервер не удовлетворён <a href="/wiki/IP-%D0%B0%D0%B4%D1%80%D0%B5%D1%81" title="IP-адрес">IP-адресом</a> клиента, например, при блокировках. Появился в HTTP/1.0.</li>
        <li><span id="404"></span><a href="/wiki/%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B0_404" class="mw-redirect" title="Ошибка 404">404 Not Found</a><sup id="cite_ref-17" class="reference"><a href="#cite_note-17">[17]</a></sup>&#160;— самая распространённая ошибка при пользовании Интернетом, основная причина&#160;— ошибка в написании адреса Web-страницы. Сервер понял запрос, но не нашёл соответствующего ресурса по указанному URI. Если серверу известно, что по этому адресу был документ, то ему желательно использовать код <a href="#410">410</a>. Ответ <code>404</code> может использоваться вместо <code><a href="#403">403</a></code>, если требуется тщательно скрыть от посторонних глаз определённые ресурсы. Появился в HTTP/1.0.</li>
        <li><span id="405"></span> 405 Method Not Allowed&#160;— указанный клиентом метод нельзя применить к текущему ресурсу. В ответе сервер должен указать доступные методы в заголовке <code>Allow</code>, разделив их запятой. Эту ошибку сервер должен возвращать, если метод ему известен, но он не применим именно к указанному в запросе ресурсу, если же указанный метод не применим на всём сервере, то клиенту нужно вернуть код <a href="#501"><code>501</code></a> (Not Implemented). Появился в HTTP/1.1.</li>
        <li><span id="406"></span> 406 Not Acceptable&#160;— запрошенный URI не может удовлетворить переданным в заголовке характеристикам. Если метод был не <code>HEAD</code>, то сервер должен вернуть список допустимых характеристик для данного ресурса. Появился в HTTP/1.1.</li>
        <li><span id="407"></span> 407 Proxy Authentication Required&#160;— ответ аналогичен коду <code><a href="#401">401</a></code> за исключением того, что аутентификация производится для прокси-сервера. Механизм аналогичен идентификации на исходном сервере. Появился в HTTP/1.1.</li>
        <li><span id="408"></span> 408 Request Timeout&#160;— время ожидания сервером передачи от клиента истекло. Клиент может повторить аналогичный предыдущему запрос в любое время. Например, такая ситуация может возникнуть при загрузке на сервер объёмного файла методом <a href="/wiki/HTTP#POST" title="HTTP"><code>POST</code></a> или <a href="/wiki/HTTP#PUT" title="HTTP"><code>PUT</code></a>. В какой-то момент передачи источник данных перестал отвечать, например, из-за повреждения <a href="/wiki/%D0%9A%D0%BE%D0%BC%D0%BF%D0%B0%D0%BA%D1%82-%D0%B4%D0%B8%D1%81%D0%BA" title="Компакт-диск">компакт-диска</a> или потери связи с другим компьютером в локальной сети. Пока клиент ничего не передаёт, ожидая от него ответа, соединение с сервером держится. Через некоторое время сервер может закрыть соединение со своей стороны, чтобы дать возможность другим клиентам сделать запрос. Этот ответ не возвращается, когда клиент принудительно остановил передачу по команде пользователя или соединение прервалось по каким-то иным причинам, так как ответ уже послать невозможно. Появился в HTTP/1.1.</li>
        <li><span id="409"></span> 409 Conflict&#160;— запрос не может быть выполнен из-за конфликтного обращения к ресурсу. Такое возможно, например, когда два клиента пытаются изменить ресурс с помощью метода <code>PUT</code>.Появился в HTTP/1.1.</li>
        <li><span id="410"></span> 410 Gone&#160;— такой ответ сервер посылает, если ресурс раньше был по указанному URL, но был удалён и теперь недоступен. Серверу в этом случае неизвестно и местоположение альтернативного документа, например, копии). Если у сервера есть подозрение, что документ в ближайшее время может быть восстановлен, то лучше клиенту передать код <code><a href="#404">404</a></code>. Появился в HTTP/1.1.</li>
        <li><span id="411"></span> 411 Length Required&#160;— для указанного ресурса клиент должен указать <code>Content-Length</code> в заголовке запроса. Без указания этого поля не стоит делать повторную попытку запроса к серверу по данному URI. Такой ответ естественен для запросов типа <code>POST</code> и <code>PUT</code>. Например, если по указанному URI производится загрузка файлов, а на сервере стоит ограничение на их объём. Тогда разумней будет проверить в самом начале заголовок <code>Content-Length</code> и сразу отказать в загрузке, чем провоцировать бессмысленную нагрузку, разрывая соединение, когда клиент действительно пришлёт слишком объёмное сообщение. Появился в HTTP/1.1.</li>
        <li><span id="412"></span> 412 Precondition Failed&#160;— возвращается, если ни одно из условных полей заголовка (If-Match и др., см. <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc7232">RFC 7232</a>) запроса не было выполнено. Появился в HTTP/1.1.</li>
        <li><span id="413"></span> 413 Request Entity Too Large&#160;— возвращается в случае, если сервер отказывается обработать запрос по причине слишком большого размера тела запроса. Сервер может закрыть соединение, чтобы прекратить дальнейшую передачу запроса. Если проблема временная, то рекомендуется в ответ сервера включить заголовок <code>Retry-After</code> с указанием времени, по истечении которого можно повторить аналогичный запрос. Появился в HTTP/1.1.</li>
        <li><span id="414"></span> 414 Request-URL Too Long&#160;— сервер не может обработать запрос из-за слишком длинного указанного URL. Такую ошибку можно спровоцировать, например, когда клиент пытается передать длинные параметры через метод <code>GET</code>, а не <code>POST</code>. Появился в HTTP/1.1.</li>
        <li><span id="415"></span> 415 Unsupported Media Type&#160;— по каким-то причинам сервер отказывается работать с указанным типом данных при данном методе. Появился в HTTP/1.1.</li>
        <li><span id="416"></span> 416 Requested Range Not Satisfiable&#160;— в поле <code>Range</code> заголовка запроса был указан диапазон за пределами ресурса и отсутствует поле <code>If-Range</code>. Если клиент передал байтовый диапазон, то сервер может вернуть реальный размер в поле <code>Content-Range</code> заголовка. Данный ответ не следует использовать при передаче типа <code>multipart/byteranges</code><span class="noprint"><sup><a href="/wiki/%D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F:%D0%A1%D1%81%D1%8B%D0%BB%D0%BA%D0%B8_%D0%BD%D0%B0_%D0%B8%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%B8" title="Википедия:Ссылки на источники">[<i>источник&#160;не&#160;указан&#160;1685&#160;дней</i>]</a></sup></span>. Введено в <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc2616">RFC 2616</a> (обновление HTTP/1.1).</li>
        <li><span id="417"></span> 417 Expectation Failed&#160;— по каким-то причинам сервер не может удовлетворить значению поля <code>Expect</code> заголовка запроса. Введено в <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc2616">RFC 2616</a> (обновление HTTP/1.1).</li>
        <li><span id="418"></span> 418 I'm a teapot — Этот код был введен в 1998 году как одна из традиционных первоапрельских шуток IETF в <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc2324">RFC 2324</a>, <a href="/wiki/HTCPCP" title="HTCPCP">Hyper Text Coffee Pot Control Protocol</a>. Не ожидается, что данный код будет поддерживаться реальными серверами.<sup id="cite_ref-:0_18-0" class="reference"><a href="#cite_note-:0-18">[18]</a></sup></li>
        <li><span id="422"></span> 422 Unprocessable Entity&#160;— сервер успешно принял запрос, может работать с указанным видом данных, в теле запроса <a href="/wiki/XML" title="XML">XML</a>-документ имеет верный синтаксис, но имеется какая-то логическая ошибка, из-за которой невозможно произвести операцию над ресурсом. Введено в <i>WebDAV</i>.</li>
        <li><span id="423"></span> 423 Locked&#160;— целевой ресурс из запроса заблокирован от применения к нему указанного метода. Введено в <a href="/wiki/WebDAV" title="WebDAV">WebDAV</a>.</li>
        <li><span id="424"></span> 424 Failed Dependency&#160;— реализация текущего запроса может зависеть от успешности выполнения другой операции. Если она не выполнена и из-за этого нельзя выполнить текущий запрос, то сервер вернёт этот код. Введено в <i>WebDAV</i>.</li>
        <li><span id="425"></span> 425 Unordered Collection&#160;— используется в расширении <i>WebDAV Advanced Collections Protocol</i><sup id="cite_ref-autogenerated1_19-0" class="reference"><a href="#cite_note-autogenerated1-19">[19]</a></sup>. Посылается, если клиент указал номер элемента в неупорядоченном списке, или запросил несколько элементов в порядке, отличающемся от серверного.</li>
        <li><span id="426"></span> 426 Upgrade Required&#160;— сервер указывает клиенту на необходимость обновить протокол. Заголовок ответа должен содержать правильно сформированные поля <code>Upgrade</code> и <code>Connection</code>. Введено в <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc2817">RFC 2817</a> для возможности перехода к <a href="/wiki/TLS" title="TLS">TLS</a> посредством HTTP.</li>
        <li><span id="428"></span> 428 Precondition Required&#160;— сервер указывает клиенту на необходимость использования в запросе заголовков условий, наподобие <code>If-Match</code>. Введено в черновике стандарта <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc6585">RFC 6585</a>.</li>
        <li><span id="429"></span> 429 Too Many Requests&#160;— клиент попытался отправить слишком много запросов за короткое время, что может указывать, например, на попытку DDoS-атаки. Может сопровождаться заголовком Retry-After, указывающим, через какое время можно повторить запрос. Введено в черновике стандарта <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc6585">RFC 6585</a>.</li>
        <li><span id="431"></span> 431 Request Header Fields Too Large&#160;— Превышена допустимая длина заголовков. Сервер не обязан отвечать этим кодом, вместо этого он может просто сбросить соединение. Введено в черновике стандарта <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc6585">RFC 6585</a>.</li>
        <li>434 Requested host unavailable - Запрашиваемый адрес недоступен<span class="noprint"><sup><a href="/wiki/%D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F:%D0%A1%D1%81%D1%8B%D0%BB%D0%BA%D0%B8_%D0%BD%D0%B0_%D0%B8%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%B8" title="Википедия:Ссылки на источники">[<i>источник&#160;не&#160;указан&#160;1122&#160;дня</i>]</a></sup></span>.</li>
        <li><span id="449"></span> 449 Retry With&#160;— возвращается сервером, если для обработки запроса от клиента поступило недостаточно информации. При этом в заголовок ответа помещается поле <code>Ms-Echo-Request</code>. Введено корпорацией <i>Microsoft</i> для <i>WebDAV</i>. В настоящий момент как минимум используется программой <i><a href="/wiki/Microsoft_Money" title="Microsoft Money">Microsoft Money</a></i>.</li>
        <li><span id="451"></span><a href="/wiki/HTTP_451" title="HTTP 451">451 Unavailable For Legal Reasons</a>&#160;— доступ к ресурсу закрыт по юридическим причинам, например, по требованию органов государственной власти или по требованию правообладателя в случае нарушения авторских прав. Введено в черновике IETF за авторством <a href="/wiki/Google" title="Google">Google</a><sup id="cite_ref-http451_11-1" class="reference"><a href="#cite_note-http451-11">[11]</a></sup>, при этом код ошибки является отсылкой к роману Рэя Брэдбери «<a href="/wiki/451_%D0%B3%D1%80%D0%B0%D0%B4%D1%83%D1%81_%D0%BF%D0%BE_%D0%A4%D0%B0%D1%80%D0%B5%D0%BD%D0%B3%D0%B5%D0%B9%D1%82%D1%83" title="451 градус по Фаренгейту">451 градус по Фаренгейту</a>». Был добавлен в стандарт 21 декабря 2015.<sup id="cite_ref-20" class="reference"><a href="#cite_note-20">[20]</a></sup></li>
    </ul>
    <h3><span class="mw-headline" id=".D0.9E.D1.88.D0.B8.D0.B1.D0.BA.D0.B0_.D1.81.D0.B5.D1.80.D0.B2.D0.B5.D1.80.D0.B0">Ошибка сервера</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&amp;veaction=edit&amp;vesection=7" class="mw-editsection-visualeditor" title="Редактировать раздел «Ошибка сервера»">править</a><span class="mw-editsection-divider"> | </span><a href="/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&amp;action=edit&amp;section=7" title="Редактировать раздел «Ошибка сервера»">править вики-текст</a><span class="mw-editsection-bracket">]</span></span></h3>
    <p>
        <span id="5xx"></span> Коды <code>5xx</code> выделены под случаи неудачного выполнения операции по вине сервера. Для всех ситуаций, кроме использования метода <code>HEAD</code>, сервер должен включать в тело сообщения объяснение, которое клиент отобразит пользователю.
    </p>
    <ul>
        <li><span id="500"></span> 500 Internal Server Error<sup id="cite_ref-21" class="reference"><a href="#cite_note-21">[21]</a></sup> — любая внутренняя ошибка сервера, которая не входит в рамки остальных ошибок класса. Появился в HTTP/1.0.</li>
        <li><span id="501"></span> 501 Not Implemented&#160;— сервер не поддерживает возможностей, необходимых для обработки запроса. Типичный ответ для случаев, когда сервер не понимает указанный в запросе метод. Если же метод серверу известен, но он не применим к данному ресурсу, то нужно вернуть ответ <a href="#405"><code>405</code></a>. Появился в HTTP/1.0.</li>
        <li><span id="502"></span> 502 Bad Gateway&#160;— сервер, выступая в роли шлюза или прокси-сервера, получил недействительное ответное сообщение от вышестоящего сервера. Появился в HTTP/1.0.</li>
        <li><span id="503"></span> 503 Service Unavailable&#160;— сервер временно не имеет возможности обрабатывать запросы по техническим причинам (обслуживание, перегрузка и прочее). В поле <code>Retry-After</code> заголовка сервер может указать время, через которое клиенту рекомендуется повторить запрос. Хотя во время перегрузки очевидным кажется сразу разрывать соединение, эффективней может оказаться установка большого значения поля <code>Retry-After</code> для уменьшения частоты избыточных запросов. Появился в HTTP/1.0.</li>
        <li><span id="504"></span> 504 Gateway Timeout&#160;— сервер в роли шлюза или прокси-сервера не дождался ответа от вышестоящего сервера для завершения текущего запроса. Появился в HTTP/1.1.</li>
        <li><span id="505"></span> 505 HTTP Version Not Supported&#160;— сервер не поддерживает или отказывается поддерживать указанную в запросе версию протокола HTTP. Появился в HTTP/1.1.</li>
        <li><span id="506"></span> 506 Variant Also Negotiates&#160;— в результате ошибочной конфигурации выбранный вариант указывает сам на себя, из-за чего процесс связывания прерывается. Экспериментальное. Введено в <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc2295">RFC 2295</a> для дополнения протокола HTTP технологией <i><a href="/w/index.php?title=Transparent_Content_Negotiation&amp;action=edit&amp;redlink=1" class="new" title="Transparent Content Negotiation (страница отсутствует)">Transparent Content Negotiation</a></i>.</li>
        <li><span id="507"></span> 507 Insufficient Storage&#160;— не хватает места для выполнения текущего запроса. Проблема может быть временной. Введено в <i>WebDAV</i>.</li>
        <li><span id="509"></span> 509 Bandwidth Limit Exceeded&#160;— используется при превышении веб-площадкой отведённого ей ограничения на потребление трафика. В данном случае владельцу площадки следует обратиться к своему хостинг-провайдеру. В настоящий момент данный код не описан ни в одном <a href="/wiki/RFC" title="RFC">RFC</a> и используется только модулем «bw/limited», входящим в панель управления хостингом <i><a href="/wiki/CPanel" title="CPanel">cPanel</a></i>, где и был введён.</li>
        <li><span id="510"></span> 510 Not Extended&#160;— на сервере отсутствует расширение, которое желает использовать клиент. Сервер может дополнительно передать информацию о доступных ему расширениях. Введено в <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc2774">RFC 2774</a> для дополнения протокола HTTP поддержкой расширений.</li>
        <li><span id="511"></span> 511 Network Authentication Required&#160;— этот ответ посылается не сервером, которому был предназначен запрос, а сервером-посредником&#160;— например, сервером провайдера&#160;— в случае, если клиент должен сначала авторизоваться в сети, например, ввести пароль для платной точки доступа к Интернету. Предполагается, что в теле ответа будет возвращена Web-форма авторизации или перенаправление на неё. Введено в черновике стандарта <a class="external mw-magiclink-rfc" rel="nofollow" href="//tools.ietf.org/html/rfc6585">RFC 6585</a>.</li>
    </ul>

</body>
</html>